//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Rule
{
    [Serializable]
    public class HakoRuleObstacleMsg : Message
    {
        public const string k_RosMessageName = "rule_msgs/HakoRuleObstacle";
        public override string RosMessageName => k_RosMessageName;

        public bool[] is_touch;

        public HakoRuleObstacleMsg()
        {
            this.is_touch = new bool[0];
        }

        public HakoRuleObstacleMsg(bool[] is_touch)
        {
            this.is_touch = is_touch;
        }

        public static HakoRuleObstacleMsg Deserialize(MessageDeserializer deserializer) => new HakoRuleObstacleMsg(deserializer);

        private HakoRuleObstacleMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.is_touch, sizeof(bool), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.is_touch);
            serializer.Write(this.is_touch);
        }

        public override string ToString()
        {
            return "HakoRuleObstacleMsg: " +
            "\nis_touch: " + System.String.Join(", ", is_touch.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
