//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ev3
{
    [Serializable]
    public class Ev3PduActuatorMsg : Message
    {
        public const string k_RosMessageName = "ev3_msgs/Ev3PduActuator";
        public override string RosMessageName => k_RosMessageName;

        public Ev3PduActuatorHeaderMsg head;
        public byte[] leds;
        public Ev3PduMotorMsg[] motors;
        public uint gyro_reset;

        public Ev3PduActuatorMsg()
        {
            this.head = new Ev3PduActuatorHeaderMsg();
            this.leds = new byte[1];
            this.motors = new Ev3PduMotorMsg[3];
            this.gyro_reset = 0;
        }

        public Ev3PduActuatorMsg(Ev3PduActuatorHeaderMsg head, byte[] leds, Ev3PduMotorMsg[] motors, uint gyro_reset)
        {
            this.head = head;
            this.leds = leds;
            this.motors = motors;
            this.gyro_reset = gyro_reset;
        }

        public static Ev3PduActuatorMsg Deserialize(MessageDeserializer deserializer) => new Ev3PduActuatorMsg(deserializer);

        private Ev3PduActuatorMsg(MessageDeserializer deserializer)
        {
            this.head = Ev3PduActuatorHeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.leds, sizeof(byte), 1);
            deserializer.Read(out this.motors, Ev3PduMotorMsg.Deserialize, 3);
            deserializer.Read(out this.gyro_reset);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.head);
            serializer.Write(this.leds);
            serializer.Write(this.motors);
            serializer.Write(this.gyro_reset);
        }

        public override string ToString()
        {
            return "Ev3PduActuatorMsg: " +
            "\nhead: " + head.ToString() +
            "\nleds: " + System.String.Join(", ", leds.ToList()) +
            "\nmotors: " + System.String.Join(", ", motors.ToList()) +
            "\ngyro_reset: " + gyro_reset.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
