//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ev3
{
    [Serializable]
    public class Ev3PduActuatorHeaderMsg : Message
    {
        public const string k_RosMessageName = "ev3_msgs/Ev3PduActuatorHeader";
        public override string RosMessageName => k_RosMessageName;

        public string name;
        public uint version;
        public long asset_time;
        public uint ext_off;
        public uint ext_size;

        public Ev3PduActuatorHeaderMsg()
        {
            this.name = "";
            this.version = 0;
            this.asset_time = 0;
            this.ext_off = 0;
            this.ext_size = 0;
        }

        public Ev3PduActuatorHeaderMsg(string name, uint version, long asset_time, uint ext_off, uint ext_size)
        {
            this.name = name;
            this.version = version;
            this.asset_time = asset_time;
            this.ext_off = ext_off;
            this.ext_size = ext_size;
        }

        public static Ev3PduActuatorHeaderMsg Deserialize(MessageDeserializer deserializer) => new Ev3PduActuatorHeaderMsg(deserializer);

        private Ev3PduActuatorHeaderMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            deserializer.Read(out this.version);
            deserializer.Read(out this.asset_time);
            deserializer.Read(out this.ext_off);
            deserializer.Read(out this.ext_size);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.version);
            serializer.Write(this.asset_time);
            serializer.Write(this.ext_off);
            serializer.Write(this.ext_size);
        }

        public override string ToString()
        {
            return "Ev3PduActuatorHeaderMsg: " +
            "\nname: " + name.ToString() +
            "\nversion: " + version.ToString() +
            "\nasset_time: " + asset_time.ToString() +
            "\next_off: " + ext_off.ToString() +
            "\next_size: " + ext_size.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
