//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ev3
{
    [Serializable]
    public class Ev3PduMotorMsg : Message
    {
        public const string k_RosMessageName = "ev3_msgs/Ev3PduMotor";
        public override string RosMessageName => k_RosMessageName;

        public int power;
        public uint stop;
        public uint reset_angle;

        public Ev3PduMotorMsg()
        {
            this.power = 0;
            this.stop = 0;
            this.reset_angle = 0;
        }

        public Ev3PduMotorMsg(int power, uint stop, uint reset_angle)
        {
            this.power = power;
            this.stop = stop;
            this.reset_angle = reset_angle;
        }

        public static Ev3PduMotorMsg Deserialize(MessageDeserializer deserializer) => new Ev3PduMotorMsg(deserializer);

        private Ev3PduMotorMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.power);
            deserializer.Read(out this.stop);
            deserializer.Read(out this.reset_angle);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.power);
            serializer.Write(this.stop);
            serializer.Write(this.reset_angle);
        }

        public override string ToString()
        {
            return "Ev3PduMotorMsg: " +
            "\npower: " + power.ToString() +
            "\nstop: " + stop.ToString() +
            "\nreset_angle: " + reset_angle.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
